-- Use este SQL se quiser criar as tabelas manualmente no Supabase.
-- O backend também cria as tabelas automaticamente quando conecta no DB_URL.
create table if not exists users(id serial primary key,name varchar(120) not null,email varchar(160) unique not null,password_hash varchar(255) not null,role varchar(30) default 'gestor',created_at timestamptz default now());
create table if not exists teams(id serial primary key,owner_id int not null references users(id),name varchar(160) not null,category varchar(80) default 'Livre',city varchar(120) default '',coach varchar(120) default '',notes text default '');
create table if not exists athletes(id serial primary key,owner_id int not null references users(id),team_id int not null references teams(id),name varchar(160) not null,position varchar(60) default '',dominant_foot varchar(20) default '',age int default 0,height float default 0,weight float default 0,strengths text default '',weaknesses text default '');
create table if not exists matches(id serial primary key,owner_id int not null references users(id),team_id int not null references teams(id),match_date date not null,opponent varchar(160) not null,location varchar(120) default '',competition varchar(120) default '',formation varchar(40) default '4-4-2',goals_for int default 0,goals_against int default 0,notes text default '');
create table if not exists scout_events(id serial primary key,owner_id int not null references users(id),match_id int not null references matches(id),athlete_id int references athletes(id),minute int default 0,event_type varchar(80) not null,zone varchar(80) default '',result varchar(80) default '',notes text default '');
create table if not exists opponent_analyses(id serial primary key,owner_id int not null references users(id),opponent varchar(160) not null,base_formation varchar(40) default '',attack_side varchar(40) default '',strong_players text default '',strengths text default '',weaknesses text default '',set_pieces_attack text default '',set_pieces_defense text default '',how_scores text default '',how_concedes text default '');
create table if not exists game_plans(id serial primary key,owner_id int not null references users(id),opponent varchar(160) not null,recommended_formation varchar(40) default '',defensive_strategy text default '',offensive_strategy text default '',individual_marking text default '',set_piece_plan text default '',substitutions text default '',ai_suggestion text default '');
