const API = 'https://datainsight-sports-analytics.onrender.com';
let token = localStorage.getItem('token');
let chart;
const $ = s => document.querySelector(s);
const authHeaders = () => ({'Content-Type':'application/json','Authorization':'Bearer '+token});
async function api(path, opts={}){ const r=await fetch(API+path,opts); if(!r.ok){throw new Error((await r.json()).detail||'Erro');} return r.json(); }
function formObj(form){ return Object.fromEntries(new FormData(form).entries()); }
function show(id){ document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden')); $('#'+id).classList.remove('hidden'); refresh(); }
function logout(){ localStorage.removeItem('token'); token=null; location.reload(); }
async function register(){ try{ const r=await api('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#name').value,email:$('#email').value,password:$('#password').value})}); token=r.token; localStorage.setItem('token',token); boot(); }catch(e){alert(e.message)} }
async function login(){ try{ const r=await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#email').value,password:$('#password').value})}); token=r.token; localStorage.setItem('token',token); boot(); }catch(e){alert(e.message)} }
async function boot(){ if(!token)return; $('#auth').classList.add('hidden'); $('#app').classList.remove('hidden'); await refresh(); }
async function refresh(){ if(!token)return; await Promise.all([loadTeams(),loadAthletes(),loadMatches(),loadDashboard(),loadScout(),loadOpponents(),loadPlans()]); }
function opt(select, data, label){ document.querySelectorAll(select).forEach(s=>{ const val=s.value; s.innerHTML='<option value="">Selecione</option>'+data.map(x=>`<option value="${x.id}">${label(x)}</option>`).join(''); s.value=val; }); }
async function loadTeams(){ const data=await api('/api/teams',{headers:authHeaders()}); opt('select[name="team_id"]',data,x=>x.name); $('#teamList').innerHTML=data.map(x=>`<div class=item><b>${x.name}</b><br><small>${x.category||''} - ${x.city||''} - Técnico: ${x.coach||''}</small><p>${x.notes||''}</p></div>`).join(''); }
async function saveTeam(e){ e.preventDefault(); await api('/api/teams',{method:'POST',headers:authHeaders(),body:JSON.stringify(formObj(e.target))}); e.target.reset(); refresh(); }
async function loadAthletes(){ const data=await api('/api/athletes',{headers:authHeaders()}); opt('select[name="athlete_id"]',data,x=>x.name+' - '+(x.position||'')); $('#athleteList').innerHTML=data.map(x=>`<div class=item><b>${x.name}</b><br><small>${x.position||''} | ${x.dominant_foot||''} | ${x.age||0} anos | ${x.height||0}m | ${x.weight||0}kg</small><p><b>Fortes:</b> ${x.strengths||''}<br><b>Melhorar:</b> ${x.weaknesses||''}</p></div>`).join(''); }
async function saveAthlete(e){ e.preventDefault(); const o=formObj(e.target); ['team_id','age'].forEach(k=>o[k]=Number(o[k]||0)); ['height','weight'].forEach(k=>o[k]=parseFloat(o[k]||0)); await api('/api/athletes',{method:'POST',headers:authHeaders(),body:JSON.stringify(o)}); e.target.reset(); refresh(); }
async function loadMatches(){ const data=await api('/api/matches',{headers:authHeaders()}); opt('select[name="match_id"]',data,x=>`${x.match_date} - ${x.opponent}`); $('#matchList').innerHTML=data.map(x=>`<div class=item><b>${x.match_date} - ${x.opponent}</b><br><small>${x.competition||''} | ${x.location||''} | ${x.formation||''}</small><p>Placar: ${x.goals_for} x ${x.goals_against}<br>${x.notes||''}</p></div>`).join(''); }
async function saveMatch(e){ e.preventDefault(); const o=formObj(e.target); ['team_id','goals_for','goals_against'].forEach(k=>o[k]=Number(o[k]||0)); await api('/api/matches',{method:'POST',headers:authHeaders(),body:JSON.stringify(o)}); e.target.reset(); refresh(); }
async function loadScout(){ const data=await api('/api/scout',{headers:authHeaders()}); $('#scoutList').innerHTML=data.map(x=>`<div class=item><b>${x.minute}' - ${x.event_type}</b><br><small>${x.zone||''} | ${x.result||''}</small><p>${x.notes||''}</p></div>`).join(''); }
async function saveScout(e){ e.preventDefault(); const o=formObj(e.target); ['match_id','athlete_id','minute'].forEach(k=>o[k]=o[k]?Number(o[k]):null); await api('/api/scout',{method:'POST',headers:authHeaders(),body:JSON.stringify(o)}); e.target.reset(); refresh(); }
async function loadOpponents(){ const data=await api('/api/opponents',{headers:authHeaders()}); $('#opponentList').innerHTML=data.map(x=>`<div class=item><b>${x.opponent}</b><br><small>Formação: ${x.base_formation||''} | Lado forte: ${x.attack_side||''}</small><p><b>Fortes:</b> ${x.strengths||''}<br><b>Fracos:</b> ${x.weaknesses||''}<br><b>Como faz gols:</b> ${x.how_scores||''}<br><b>Como sofre:</b> ${x.how_concedes||''}</p></div>`).join(''); }
async function saveOpponent(e){ e.preventDefault(); await api('/api/opponents',{method:'POST',headers:authHeaders(),body:JSON.stringify(formObj(e.target))}); e.target.reset(); refresh(); }
async function loadPlans(){ const data=await api('/api/gameplans',{headers:authHeaders()}); $('#planList').innerHTML=data.map(x=>`<div class=item><b>${x.opponent} - ${x.recommended_formation||''}</b><p><b>Defesa:</b> ${x.defensive_strategy||''}<br><b>Ataque:</b> ${x.offensive_strategy||''}<br><b>Marcação:</b> ${x.individual_marking||''}<br><b>Bola parada:</b> ${x.set_piece_plan||''}<br><b>Sugestão:</b> ${x.ai_suggestion||''}</p></div>`).join(''); }
async function savePlan(e){ e.preventDefault(); await api('/api/gameplans',{method:'POST',headers:authHeaders(),body:JSON.stringify(formObj(e.target))}); e.target.reset(); refresh(); }
async function loadDashboard(){ const d=await api('/api/dashboard',{headers:authHeaders()}); $('#cards').innerHTML=[['Times',d.teams],['Atletas',d.athletes],['Jogos',d.matches],['Vitórias',d.wins],['Empates',d.draws],['Derrotas',d.losses],['Gols pró',d.goals_for],['Gols contra',d.goals_against]].map(x=>`<div class=metric><span>${x[0]}</span><br><b>${x[1]}</b></div>`).join(''); const labels=Object.keys(d.event_counts); const vals=Object.values(d.event_counts); if(chart) chart.destroy(); chart=new Chart($('#chart'),{type:'bar',data:{labels,datasets:[{label:'Eventos de scout',data:vals}]},options:{responsive:true,plugins:{legend:{display:false}}}}); }
boot();
